services:
  app-dev:
    build:
      context: ..
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: '1'
      WATCHPACK_POLLING: 'true'
      CHOKIDAR_USEPOLLING: 'true'
      # Use o mesmo .env.docker
      # docker-compose não aceita --env-file aqui, então montamos abaixo
    env_file:
      - ../.env.docker
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
      - minio
    networks:
      - default

volumes:
  node_modules:
